function CTextButton(b,g,d,e,c,k,a,m){var l,f,n,w,u,r,p,v,t,h,x,y,z,A={};this._init=function(a,c,b,d,e,r,p){l=!1;f=1;z=!1;v=[];t=[];var g=createBitmap(b),n=Math.ceil(p/20);y=new createjs.Text(d,"bold "+p+"px "+e,"#000000");y.textAlign="center";y.textBaseline="alphabetic";var k=y.getBounds();y.x=b.width/2+n;y.y=Math.floor(b.height/2+k.height/3+n)+m;y.alpha=.5;x=new createjs.Text(d,"bold "+p+"px "+e,r);x.textAlign="center";x.textBaseline="alphabetic";k=x.getBounds();x.x=b.width/2;x.y=Math.floor(b.height/
2+k.height/3)+m;h=new createjs.Container;h.x=a;h.y=c;h.regX=b.width/2;h.regY=b.height/2;h.addChild(g,y,x);s_oStage.addChild(h);this._initListener()};this.setExtraData=function(a,b){A[a]=b};this.getExtraData=function(a){return A[a]};this.unload=function(){h.off("mousedown");h.off("pressup");s_oStage.removeChild(h)};this.setUsed=function(a){z=a};this.getUsed=function(){return z};this.getID=function(){return p};this.setCursorType=function(a){h.cursor=a};this.setTextCenterX=function(a){x+=a;x+=a};this.changeChildIndex=
function(a){s_oStage.setChildIndex(h,a)};this.setVisible=function(a){h.visible=a};this.getVisible=function(){return h.visible};this._initListener=function(){oParent=this;h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){v[a]=b;t[a]=c};this.addEventListenerWithParams=function(a,b,c,f,d,e,h,g){v[a]=b;t[a]=c;n=f;w=h;u=d;r=e;p=g};this.buttonRelease=function(){l||(h.scaleX=1*f,h.scaleY=1*f,v[ON_MOUSE_UP]&&v[ON_MOUSE_UP].call(t[ON_MOUSE_UP],n,u,
r,w,p))};this.buttonDown=function(){l||(h.scaleX=.9*f,h.scaleY=.9*f,v[ON_MOUSE_DOWN]&&v[ON_MOUSE_DOWN].call(t[ON_MOUSE_DOWN],n,u,r,w,p))};this.setTextPosition=function(a){x.y=a;y.y=a+2};this.getText=function(){return x.text};this.setText=function(a){x.text=a;y.text=a};this.setPosition=function(a,b){h.x=a;h.y=b};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};this.block=function(a){l=
a};this.setScale=function(a){f=a;h.scaleX=a;h.scaleY=a};this._init(b,g,d,e,c,k,a);return this}
function CText(b,g,d,e,c,k,a,m){var l,f,n;this._init=function(a,b,c,d,e,g,h){var k=createBitmap(c),y=Math.ceil(h/20);n=new createjs.Text(d,"bold "+h+"px "+e,"#000000");n.textAlign="center";n.textBaseline="alphabetic";var z=n.getBounds();n.x=c.width/2+y;n.y=Math.floor(c.height/2+z.height/3+y)+m;n.alpha=.5;f=new createjs.Text(d,"bold "+h+"px "+e,g);f.textAlign="center";f.textBaseline="alphabetic";z=f.getBounds();f.x=c.width/2;f.y=Math.floor(c.height/2+z.height/3)+m;l=new createjs.Container;l.x=a;l.y=
b;l.regX=c.width/2;l.regY=c.height/2;l.addChild(k,n,f);s_oStage.addChild(l);this._initListener()};this._initListener=function(){oParent=this};this.setText=function(a){f.text=a;n.text=a};this.changeChildIndex=function(a){null!==d?s_oStage.setChildIndex(l,a):s_oStage.setChildIndex(f,a)};this.setVisible=function(a){l.visible=a};this.unload=function(){s_oStage.removeChild(l)};this._init(b,g,d,e,c,k,a);return this}
function CPreloader(){var b,g,d,e,c,k,a;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.png");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();a=new createjs.Container;s_oStage.addChild(a)};this.unload=function(){a.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(k).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var m=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));a.addChild(m);m=s_oSpriteLibrary.getSprite("progress_bar");e=createBitmap(m);e.x=CANVAS_WIDTH/2-m.width/2;e.y=CANVAS_HEIGHT-370;a.addChild(e);b=m.width;g=m.height;c=new createjs.Shape;c.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,1,g);a.addChild(c);e.mask=
c;d=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT-325;d.shadow=new createjs.Shadow("#000",2,2,2);d.textBaseline="alphabetic";d.textAlign="center";a.addChild(d);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=0;a.addChild(k)};this.refreshLoader=function(a){d.text=a+"%";c.graphics.clear();a=Math.floor(a*b/100);c.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,a,g)};this._init()}
function CMenu(){var b,g,d,e,c,k;this._init=function(){d=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(d);var a=s_oSpriteLibrary.getSprite("but_play");e=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+560,a);e.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a=s_oSpriteLibrary.getSprite("audio_icon"),b=CANVAS_WIDTH-a.height/2-PADDING,g=a.height/2+PADDING,k=new CToggle(b,g,a,s_bAudioActive),k.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);!1===s_bMobile&&(k.setCursorType("pointer"),e.setCursorType("pointer"));c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(c);createjs.Tween.get(c).to({alpha:0},1E3).call(function(){s_oStage.removeChild(c);c=null});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){e.unload();e=null;s_oStage.removeChild(d);d=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k.unload(),k=null;s_oMenu=null};this.refreshButtonPos=function(a,
c){k.setPosition(b-a,c+g)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoLanguage()};s_oMenu=this;this._init()}var s_oMenu=null;
function CMain(b){var g,d=0,e=0,c=STATE_LOADING,k,a,m,l;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile;s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;l="json/QUIZLogic.json";a=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this.loadJSON();this._loadImages();g=!0};this.onLoadedJSON=function(a){s_aQuestions=a};this.loadJSON=function(){jQuery.getJSON(l,this.onLoadedJSON)};this.soundLoaded=function(){d++;a.refreshLoader(Math.floor(d/e*100));d===e&&(a.unload(),!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&(s_oSoundtrack=createjs.Sound.play("soundtrack",
{loop:-1}))};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","gameover"),createjs.Sound.registerSound("./sounds/guessed.ogg",
"guessed"),createjs.Sound.registerSound("./sounds/wrong.ogg","wrong")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.mp3","click"),createjs.Sound.registerSound("./sounds/game_over.mp3","gameover"),createjs.Sound.registerSound("./sounds/guessed.mp3","guessed"),createjs.Sound.registerSound("./sounds/wrong.mp3",
"wrong")),e+=5)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_gameover","./sprites/bg_gameover.png");s_oSpriteLibrary.addSprite("load_level","./sprites/load_level.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");
s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("curtain_dx","./sprites/curtain_dx.jpg");s_oSpriteLibrary.addSprite("curtain_sx","./sprites/curtain_sx.jpg");s_oSpriteLibrary.addSprite("logo","./sprites/logo.png");s_oSpriteLibrary.addSprite("logo_small","./sprites/logo_small.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("letterbox","./sprites/letterbox.png");s_oSpriteLibrary.addSprite("letter","./sprites/letter.png");
s_oSpriteLibrary.addSprite("money_panel","./sprites/money_panel.png");s_oSpriteLibrary.addSprite("level_panel","./sprites/level_panel.png");s_oSpriteLibrary.addSprite("success","./sprites/success.png");s_oSpriteLibrary.addSprite("mistake","./sprites/mistake.png");s_oSpriteLibrary.addSprite("but_next","./sprites/but_next.png");s_oSpriteLibrary.addSprite("text_copyright","./sprites/text_copyright.png");s_oSpriteLibrary.addSprite("but_flag_it","./sprites/but_flag_it.png");s_oSpriteLibrary.addSprite("but_flag_en",
"./sprites/but_flag_en.png");s_oSpriteLibrary.addSprite("but_flag_fr","./sprites/but_flag_fr.png");s_oSpriteLibrary.addSprite("but_flag_es","./sprites/but_flag_es.png");s_oSpriteLibrary.addSprite("but_flag_ger","./sprites/but_flag_ger.png");s_oSpriteLibrary.addSprite("but_flag_por","./sprites/but_flag_por.png");s_oSpriteLibrary.addSprite("but_add_a_letter","./sprites/but_add_a_letter.png");s_oSpriteLibrary.addSprite("but_remove_letters","./sprites/but_remove_letters.png");s_oSpriteLibrary.addSprite("ImgHome1",
"./sprites/ImgHome1.png");s_oSpriteLibrary.addSprite("ImgHome2","./sprites/ImgHome2.jpg");s_oSpriteLibrary.addSprite("ImgHome3","./sprites/ImgHome3.jpg");s_oSpriteLibrary.addSprite("ImgHome4","./sprites/ImgHome4.jpg");s_oSpriteLibrary.addSprite("ImgCat1","./sprites/ImgCat1.jpg");s_oSpriteLibrary.addSprite("ImgCat2","./sprites/ImgCat2.jpg");s_oSpriteLibrary.addSprite("ImgCat3","./sprites/ImgCat3.jpg");s_oSpriteLibrary.addSprite("ImgCat4","./sprites/ImgCat4.jpg");s_oSpriteLibrary.addSprite("ImgHappy1",
"./sprites/ImgHappy1.jpg");s_oSpriteLibrary.addSprite("ImgHappy2","./sprites/ImgHappy2.jpg");s_oSpriteLibrary.addSprite("ImgHappy3","./sprites/ImgHappy3.jpg");s_oSpriteLibrary.addSprite("ImgHappy4","./sprites/ImgHappy4.jpg");s_oSpriteLibrary.addSprite("ImgDrink1","./sprites/ImgDrink1.jpg");s_oSpriteLibrary.addSprite("ImgDrink2","./sprites/ImgDrink2.jpg");s_oSpriteLibrary.addSprite("ImgDrink3","./sprites/ImgDrink3.jpg");s_oSpriteLibrary.addSprite("ImgDrink4","./sprites/ImgDrink4.jpg");s_oSpriteLibrary.addSprite("ImgMinute1",
"./sprites/ImgMinute1.jpg");s_oSpriteLibrary.addSprite("ImgMinute2","./sprites/ImgMinute2.jpg");s_oSpriteLibrary.addSprite("ImgMinute3","./sprites/ImgMinute3.jpg");s_oSpriteLibrary.addSprite("ImgMinute4","./sprites/ImgMinute4.jpg");s_oSpriteLibrary.addSprite("ImgSound1","./sprites/ImgSound1.jpg");s_oSpriteLibrary.addSprite("ImgSound2","./sprites/ImgSound2.jpg");s_oSpriteLibrary.addSprite("ImgSound3","./sprites/ImgSound3.jpg");s_oSpriteLibrary.addSprite("ImgSound4","./sprites/ImgSound4.jpg");s_oSpriteLibrary.addSprite("ImgCacao1",
"./sprites/ImgCacao1.jpg");s_oSpriteLibrary.addSprite("ImgCacao2","./sprites/ImgCacao2.jpg");s_oSpriteLibrary.addSprite("ImgCacao3","./sprites/ImgCacao3.jpg");s_oSpriteLibrary.addSprite("ImgCacao4","./sprites/ImgCacao4.jpg");s_oSpriteLibrary.addSprite("ImgFull1","./sprites/ImgFull1.jpg");s_oSpriteLibrary.addSprite("ImgFull2","./sprites/ImgFull2.jpg");s_oSpriteLibrary.addSprite("ImgFull3","./sprites/ImgFull3.jpg");s_oSpriteLibrary.addSprite("ImgFull4","./sprites/ImgFull4.jpg");s_oSpriteLibrary.addSprite("ImgCold1",
"./sprites/ImgCold1.jpg");s_oSpriteLibrary.addSprite("ImgCold2","./sprites/ImgCold2.jpg");s_oSpriteLibrary.addSprite("ImgCold3","./sprites/ImgCold3.jpg");s_oSpriteLibrary.addSprite("ImgCold4","./sprites/ImgCold4.jpg");s_oSpriteLibrary.addSprite("ImgViolet1","./sprites/ImgViolet1.jpg");s_oSpriteLibrary.addSprite("ImgViolet2","./sprites/ImgViolet2.jpg");s_oSpriteLibrary.addSprite("ImgViolet3","./sprites/ImgViolet3.jpg");s_oSpriteLibrary.addSprite("ImgViolet4","./sprites/ImgViolet4.jpg");s_oSpriteLibrary.addSprite("ImgChord1",
"./sprites/ImgChord1.jpg");s_oSpriteLibrary.addSprite("ImgChord2","./sprites/ImgChord2.jpg");s_oSpriteLibrary.addSprite("ImgChord3","./sprites/ImgChord3.jpg");s_oSpriteLibrary.addSprite("ImgColors1","./sprites/ImgColors1.jpg");s_oSpriteLibrary.addSprite("ImgColors2","./sprites/ImgColors2.jpg");s_oSpriteLibrary.addSprite("ImgColors3","./sprites/ImgColors3.jpg");s_oSpriteLibrary.addSprite("ImgColors4","./sprites/ImgColors4.jpg");s_oSpriteLibrary.addSprite("ImgRubber1","./sprites/ImgRubber1.jpg");s_oSpriteLibrary.addSprite("ImgRubber2",
"./sprites/ImgRubber2.jpg");s_oSpriteLibrary.addSprite("ImgRubber3","./sprites/ImgRubber3.jpg");s_oSpriteLibrary.addSprite("ImgRubber4","./sprites/ImgRubber4.jpg");s_oSpriteLibrary.addSprite("ImgDelete1","./sprites/ImgDelete1.jpg");s_oSpriteLibrary.addSprite("ImgDelete2","./sprites/ImgDelete2.jpg");s_oSpriteLibrary.addSprite("ImgDelete3","./sprites/ImgDelete3.jpg");s_oSpriteLibrary.addSprite("ImgDelete4","./sprites/ImgDelete4.jpg");s_oSpriteLibrary.addSprite("ImgClimb1","./sprites/ImgClimb1.jpg");
s_oSpriteLibrary.addSprite("ImgClimb2","./sprites/ImgClimb2.jpg");s_oSpriteLibrary.addSprite("ImgClimb3","./sprites/ImgClimb3.jpg");s_oSpriteLibrary.addSprite("ImgClimb4","./sprites/ImgClimb4.jpg");s_oSpriteLibrary.addSprite("ImgOrange1","./sprites/ImgOrange1.jpg");s_oSpriteLibrary.addSprite("ImgOrange2","./sprites/ImgOrange2.jpg");s_oSpriteLibrary.addSprite("ImgOrange3","./sprites/ImgOrange3.jpg");s_oSpriteLibrary.addSprite("ImgOrange4","./sprites/ImgOrange4.jpg");s_oSpriteLibrary.addSprite("ImgBed1",
"./sprites/ImgBed1.jpg");s_oSpriteLibrary.addSprite("ImgBed2","./sprites/ImgBed2.jpg");s_oSpriteLibrary.addSprite("ImgBed3","./sprites/ImgBed3.jpg");s_oSpriteLibrary.addSprite("ImgBed4","./sprites/ImgBed4.jpg");s_oSpriteLibrary.addSprite("ImgIsland1","./sprites/ImgIsland1.jpg");s_oSpriteLibrary.addSprite("ImgIsland2","./sprites/ImgIsland2.jpg");s_oSpriteLibrary.addSprite("ImgIsland3","./sprites/ImgIsland3.jpg");s_oSpriteLibrary.addSprite("ImgIsland4","./sprites/ImgIsland4.jpg");s_oSpriteLibrary.addSprite("ImgWine1",
"./sprites/ImgWine1.jpg");s_oSpriteLibrary.addSprite("ImgWine2","./sprites/ImgWine2.jpg");s_oSpriteLibrary.addSprite("ImgWine3","./sprites/ImgWine3.jpg");s_oSpriteLibrary.addSprite("ImgWine4","./sprites/ImgWine4.jpg");s_oSpriteLibrary.addSprite("ImgRound1","./sprites/ImgRound1.jpg");s_oSpriteLibrary.addSprite("ImgRound2","./sprites/ImgRound2.jpg");s_oSpriteLibrary.addSprite("ImgRound3","./sprites/ImgRound3.jpg");s_oSpriteLibrary.addSprite("ImgRound4","./sprites/ImgRound4.jpg");s_oSpriteLibrary.addSprite("ImgIron1",
"./sprites/ImgIron1.jpg");s_oSpriteLibrary.addSprite("ImgIron2","./sprites/ImgIron2.jpg");s_oSpriteLibrary.addSprite("ImgIron3","./sprites/ImgIron3.jpg");s_oSpriteLibrary.addSprite("ImgIron4","./sprites/ImgIron4.jpg");s_oSpriteLibrary.addSprite("but_menu","./sprites/but_menu.png");s_oSpriteLibrary.addSprite("shadow","./sprites/shadow_of_images.png");e+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){d++;a.refreshLoader(Math.floor(d/e*100))};this._onAllImagesLoaded=
function(){a.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;c=STATE_MENU};this.gotoGame=function(a){m=new CGame(a,k);c=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoGameOver=function(a){new CGameOver(a)};this.gotoLanguage=function(){new CLanguageMenu};this.stopUpdate=function(){g=!1;createjs.Ticker.paused=!0;$("#block_game").css("display",
"block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();g=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==g){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);c===STATE_GAME&&m.update();s_oStage.update(a)}};s_oMain=this;k=b;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_oCanvas,s_iLanguageSelected,s_oSpriteSheetLora,s_aQuestions;
function CLanguageMenu(){var b,g,d,e,c,k,a,m,l,f,n,w,u,r,p,v;this._init=function(){p=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(p);var t=s_oSpriteLibrary.getSprite("logo_small");b=CANVAS_WIDTH/2-540+PADDING;g=CANVAS_HEIGHT/2-840+PADDING;v=createBitmap(t);v.x=b;v.y=g;v.regX=t.width/2;v.regY=t.height/2;s_oStage.addChild(v);u=new createjs.Text(TEXT_SELECT_LANG,"bold 104px "+PRIMARY_FONT,"#ff21fe");u.textAlign="center";u.textBaseline="alphabetic";u.x=CANVAS_WIDTH/2;u.y=CANVAS_HEIGHT/
2-300;s_oStage.addChild(u);r=new createjs.Text(TEXT_SELECT_LANG,"bold 104px "+PRIMARY_FONT,"#ffffff");r.textAlign="center";r.textBaseline="alphabetic";r.x=CANVAS_WIDTH/2;r.y=CANVAS_HEIGHT/2-300;r.outline=4;s_oStage.addChild(r);t=s_oSpriteLibrary.getSprite("but_flag_it");a=new CGfxButton(CANVAS_WIDTH/2+350,CANVAS_HEIGHT/2-100,t);a.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,2);a.regX=128;a.regY=90;t=s_oSpriteLibrary.getSprite("but_flag_en");m=new CGfxButton(CANVAS_WIDTH/2-350,
CANVAS_HEIGHT/2-100,t);m.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,0);m.regX=128;m.regY=90;t=s_oSpriteLibrary.getSprite("but_flag_fr");l=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2-100,t);l.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,1);l.regX=128;l.regY=90;t=s_oSpriteLibrary.getSprite("but_flag_es");f=new CGfxButton(CANVAS_WIDTH/2+350,CANVAS_HEIGHT/2+150,t);f.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,3);f.regX=128;f.regY=
90;t=s_oSpriteLibrary.getSprite("but_flag_ger");n=new CGfxButton(CANVAS_WIDTH/2-350,CANVAS_HEIGHT/2+150,t);n.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,4);n.regX=128;n.regY=90;t=s_oSpriteLibrary.getSprite("but_flag_por");w=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+150,t);w.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,5);w.regX=128;w.regY=90;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)t=s_oSpriteLibrary.getSprite("audio_icon"),d=CANVAS_WIDTH-t.height/
2-PADDING,e=t.height/2+PADDING,k=new CToggle(d,e,t,s_bAudioActive),k.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(c);createjs.Tween.get(c).to({alpha:0},1E3).call(function(){s_oStage.removeChild(c);c=null});!1===s_bMobile&&(k.setCursorType("pointer"),m.setCursorType("pointer"),f.setCursorType("pointer"),l.setCursorType("pointer"),n.setCursorType("pointer"),a.setCursorType("pointer"),
w.setCursorType("pointer"));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){a.unload();a=null;m.unload();m=null;l.unload();l=null;f.unload();f=null;n.unload();n=null;w.unload();w=null;s_oStage.removeChild(r,u,v);v=u=r=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k.unload(),k=null;s_oMenu=null};this.refreshButtonPos=function(a,c){k.setPosition(d-a,c+e);v.x=b+a;v.y=g+c};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=
function(a){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");$(s_oMain).trigger("start_session");s_oMain.gotoGame(a)};s_oLanguageMenu=this;this._init()}var s_oLanguageMenu=null;TEXT_GAMEOVER="GAME OVER";TEXT_SCORE="SCORE";TEXT_LEVEL="LEVEL";TEXT_PT="PT";TEXT_HELP="Ghiceste cuvantul cat mai repede posibil!Daca te folosesti de ajutor, scorul tau va scadea!";TEXT_HELP2="Add a random\nletters to the\nsolution. This help\nwill cost you ";TEXT_HELP3="Remove some letters from the display. It will cost you ";
TEXT_SELECT_LANG="SELECT LANGUAGE";TEXT_CONGRATULATIONS="Congratulations!";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CInterface(b){var g,d,e,c,k,a,m,l,f,n,w,u,r,p,v,t,h,x,y,z,A,q,B,D,C,E,F;this._init=function(){h=TIME_FOR_EVERY_WORD;x=!0;var q=s_oSpriteLibrary.getSprite("logo_small");g=CANVAS_WIDTH/2-540+PADDING;d=CANVAS_HEIGHT/2-840+PADDING;D=createBitmap(q);D.x=g;D.y=d;D.regX=q.width/2;D.regY=q.height/2;s_oStage.addChild(D);q=s_oSpriteLibrary.getSprite("but_exit");k=CANVAS_WIDTH-q.height/2-PADDING;a=q.height/2+PADDING;f=new CGfxButton(k,a,q,!0);f.addEventListener(ON_MOUSE_UP,this._onExit,this);e=CANVAS_WIDTH-
q.width/2-10-165-PADDING;c=q.height/2+PADDING;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q=s_oSpriteLibrary.getSprite("audio_icon"),l=new CToggle(e,c,q,s_bAudioActive),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);q=s_oSpriteLibrary.getSprite("shadow");A=createBitmap(q);A.x=CANVAS_WIDTH/2;A.y=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+50;A.regX=q.width/2;A.regY=q.height/2;s_oStage.addChild(A);w=new createjs.Text(TEXT_LEVEL+"/n1","bold 60px "+PRIMARY_FONT,"#ff21fe");w.textAlign="center";w.textBaseline=
"alphabetic";w.y=-15;u=new createjs.Text(TEXT_LEVEL+"/n1","bold 60px "+PRIMARY_FONT,"#ffffff");u.textAlign="center";u.textBaseline="alphabetic";u.outline=6;u.y=-15;q=s_oSpriteLibrary.getSprite("level_panel");r=createBitmap(q);r.regX=q.width/2;r.regY=q.height/2;p=new createjs.Container;p.x=CANVAS_WIDTH/2;p.y=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-370;p.addChild(r,u,w);s_oStage.addChild(p);q=s_oSpriteLibrary.getSprite("money_panel");v=new CText(CANVAS_WIDTH/2-300,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-340,
q,b+TEXT_PT,PRIMARY_FONT,"#ffffff",66,-10);s_oStage.addChild(y);!0===BONUS_TIME?(t=new CText(CANVAS_WIDTH/2+300,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-340,q,h+"s",PRIMARY_FONT,"#ffffff",66,-10),s_oStage.addChild(z)):h=0;this.helpPanel();this.refreshButtonPos(s_iOffsetX,s_iOffsetY);!1===s_bMobile&&(f.setCursorType("pointer"),l.setCursorType("pointer"))};this.helpPanel=function(){var a=s_oSpriteLibrary.getSprite("bg_gameover");n=createBitmap(a);n.addEventListener("click",function(){});s_oStage.addChild(n);
q=new createjs.Text(TEXT_HELP,"bold 70px "+PRIMARY_FONT,"#ff21fe");q.textAlign="left";q.textBaseline="alphabetic";q.lineWidth=600;q.x=CANVAS_WIDTH/2-260;q.y=CANVAS_HEIGHT/2-150;s_oStage.addChild(q);B=new createjs.Text(TEXT_HELP,"bold 70px "+PRIMARY_FONT,"#ffffff");B.textAlign="left";B.textBaseline="alphabetic";B.lineWidth=600;B.x=CANVAS_WIDTH/2-260;B.y=CANVAS_HEIGHT/2-150;B.outline=3;s_oStage.addChild(B);a=s_oSpriteLibrary.getSprite("but_next");C=new CGfxButton(CANVAS_WIDTH/2+460,CANVAS_HEIGHT/2,
a);C.addEventListener(ON_MOUSE_UP,this._onNextHelp2,this);0==s_bMobile&&C.setCursorType("pointer")};this._onNextHelp2=function(){C.unload();C=null;this.helpPanel2()};this.helpPanel2=function(){var a=s_oSpriteLibrary.getSprite("but_next");C=new CGfxButton(CANVAS_WIDTH/2+460,CANVAS_HEIGHT/2,a);C.addEventListener(ON_MOUSE_UP,this._onStartGame,this);0==s_bMobile&&C.setCursorType("pointer");a=s_oSpriteLibrary.getSprite("but_remove_letters");F=createBitmap(a);F.x=CANVAS_WIDTH/2-340;F.y=CANVAS_HEIGHT/2+
240;F.regX=a.width/2;F.regY=a.height/2;s_oStage.addChild(F);a=s_oSpriteLibrary.getSprite("but_add_a_letter");E=createBitmap(a);E.x=CANVAS_WIDTH/2-340;E.y=CANVAS_HEIGHT/2-145;E.regX=a.width/2;E.regY=a.height/2;s_oStage.addChild(E);q.text=TEXT_HELP2+COST_FOR_REMOVE_LETTERS+TEXT_PT+"."+TEXT_HELP3+COST_OF_A_LETTER+TEXT_PT+".";q.x=CANVAS_WIDTH/2-190;q.y=CANVAS_HEIGHT/2-230;B.text=TEXT_HELP2+COST_FOR_REMOVE_LETTERS+TEXT_PT+"."+TEXT_HELP3+COST_OF_A_LETTER+TEXT_PT+".";B.x=CANVAS_WIDTH/2-190;B.y=CANVAS_HEIGHT/
2-230};this._onStartGame=function(){s_oStage.removeChild(B,q,n,E,F);C.unload();q=n=B=C=null;x=!1;F=E=null};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l.unload(),l=null;s_oStage.removeChild(A);A=null;f.unload();f=null;s_oStage.removeChild(p);p=null;s_oStage.removeChild(w);w=null;v.unload();v=null;s_oStage.removeChild(y);y=null;s_oStage.removeChild(z);z=null;t.unload();t=null;s_oStage.removeChild(m);m=null;null!==n&&n.unload();s_oInterface=null};this.addedMoneyAnim=function(a,
c,b){var q;0<a?(b=new createjs.Text("+"+a,"bold 66px "+PRIMARY_FONT,b),a=new createjs.Text("+"+a,"bold 66px "+PRIMARY_FONT,"#ffffff")):(b=new createjs.Text(a,"bold 66px "+PRIMARY_FONT,b),a=new createjs.Text(a,"bold 66px "+PRIMARY_FONT,"#ffffff"));b.textAlign="center";b.textBaseline="alphabetic";a.textAlign="center";a.textBaseline="alphabetic";a.outline=4;q=new createjs.Container;q.x=CANVAS_WIDTH/2-150;q.y=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-330;q.addChild(b,a);s_oStage.addChild(q);createjs.Tween.get(q).to({y:CANVAS_HEIGHT/
2-500},c);createjs.Tween.get(q).to({alpha:0},c).call(function(){s_oStage.removeChild(q);q=null})};this.setStoppedTime=function(a){x=a};this.resetCounter=function(){h=TIME_FOR_EVERY_WORD;t.setText(h+"s")};this.refreshButtonPos=function(b,q){f.setPosition(k-b,q+a);D.x=g+b;D.y=d+q;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(e-b,q+c)};this.refreshMoney=function(a){v.setText(a+"PT")};this.refreshNuMLevel=function(a){a+=1;w.text=TEXT_LEVEL+"\n"+a;u.text=TEXT_LEVEL+"\n"+a};this.getCount=function(){return Math.round(h)};
this.update=function(){if(0<h&&!1===x){var a=createjs.Ticker.getFPS();h-=1/a;t.setText(Math.round(h)+"s")}};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CGfxButton(b,g,d){var e,c,k,a,m,l,f,n,w,u;this._init=function(b,d,f){e=!1;u=1;c=[];k=[];a=createBitmap(f);a.x=b;a.y=d;a.regX=f.width/2;a.regY=f.height/2;s_oStage.addChild(a);this._initListener()};this.changeChildIndex=function(b){s_oStage.setChildIndex(a,b)};this.unload=function(){a.off("mousedown",this.buttonDown);a.off("pressup",this.buttonRelease);s_oStage.removeChild(a)};this.setVisible=function(b){a.visible=b};this.getVisible=function(){return a.visible};this._initListener=function(){a.on("mousedown",
this.buttonDown);a.on("pressup",this.buttonRelease)};this.setCursorType=function(b){a.cursor=b};this.addEventListener=function(a,b,d){c[a]=b;k[a]=d};this.addEventListenerWithParams=function(a,b,d,e,h,g,u,z){c[a]=b;k[a]=d;m=e;l=u;f=h;n=g;w=z};this.buttonRelease=function(){e||(a.scaleX=1*u,a.scaleY=1*u,c[ON_MOUSE_UP]&&c[ON_MOUSE_UP].call(k[ON_MOUSE_UP],m,f,n,l,w))};this.buttonDown=function(){e||(a.scaleX=.95*u,a.scaleY=.95*u,c[ON_MOUSE_DOWN]&&c[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN],m,f,n,l,w))};this.getScale=
function(){return u};this.setPosition=function(b,c){a.x=b;a.y=c};this.setX=function(b){a.x=b};this.setY=function(b){a.y=b};this.getButtonImage=function(){return a};this.getX=function(){return a.x};this.getY=function(){return a.y};this.block=function(a){e=a};this.setScale=function(b){u=b;a.scaleX=b;a.scaleY=b};this._init(b,g,d);return this}
function CGameSettings(b,g){var d,e,c=[],k=[],a,m,l,f,n,w,u,r,p,v,t,h,x,y,z,A;this._init=function(){d=b;h=g;w=0;m=[];l=[];f=[];x=[];z=[];y=0;A=!0;4<NUMBER_QUEST_IMAGE&&(NUMBER_QUEST_IMAGE=4);for(a=0;a<N_MAX_WORDS_TO_GUESS;a++)c[a]=Array(NUMBER_QUEST_IMAGE),k[a]=Array(NUMBER_QUEST_IMAGE);for(var q=0;q<NUMBER_OF_WORDS;q++)z[q]=q;z=shuffle(z);this.loadQuest();q=s_oSpriteLibrary.getSprite("success");p=createBitmap(q);p.x=CANVAS_WIDTH/2;p.y=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+50;p.regX=q.width/2;p.regY=
q.height/2;p.visible=!1;s_oStage.addChild(p);q=s_oSpriteLibrary.getSprite("mistake");r=createBitmap(q);r.x=CANVAS_WIDTH/2;r.y=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+50;r.regX=q.width/2;r.regY=q.height/2;r.visible=!1;s_oStage.addChild(r);q=s_oSpriteLibrary.getSprite("but_next");u=new CGfxButton(CANVAS_WIDTH/2+430,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+700,q);u.addEventListener(ON_MOUSE_UP,this._onNextLevel,this);u.setVisible(!1);u.setCursorType("pointer");q=s_oSpriteLibrary.getSprite("but_remove_letters");
v=new CGfxButton(CANVAS_WIDTH/2-100,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+940,q);v.addEventListener(ON_MOUSE_UP,this.removeSomeLetters,this);v.setCursorType("pointer");q=s_oSpriteLibrary.getSprite("but_add_a_letter");t=new CGfxButton(CANVAS_WIDTH/2+100,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+940,q);t.addEventListener(ON_MOUSE_UP,this.addALetter,this);t.setCursorType("pointer")};this.loadQuest=function(){e=s_aQuestions[z[h]].answer[d];for(var a=0;a<NUMBER_QUEST_IMAGE;a++){var b=s_oSpriteLibrary.getSprite(s_aQuestions[z[h]].img[0].file[a]);
c[h][a]=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT,b);b=s_oSpriteLibrary.getSprite("text_copyright");k[h][a]=new CText(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+320,b,s_aQuestions[z[h]].img[0].copyright[a],PRIMARY_FONT,"#ffffff",25,0);k[h][a].setVisible(!1)}};this.unloadQuest=function(b){for(var d=0;4>d;d++)c[b][d].unload(),c[b][d]=null,k[b][d].unload(),k[b][d]=null;for(a=0;a<n;a++)m[a].unload(),m[a]=null;for(a=0;a<NUM_OF_SPAWN_LETTER;a++)f[a].unload(),f[a]=null};
this.unload=function(){t.unload();t=null;s_oStage.removeChild(r);r=null;s_oStage.removeChild(p);p=null;v.unload();v=null;this.unloadQuest(h);s_oGameSettings=null};this.removeSomeLetters=function(){if(!(s_oGame.getMoney()<COST_FOR_REMOVE_LETTERS-1)){for(var a=[],b=0;b<NUM_OF_SPAWN_LETTER;b++)f[b].getVisible()&&a.push(f[b]);for(var c=3,d=!1,b=0;b<a.length;b++){for(var g=!0,h=0;h<n;h++)if(a[b].getText()===e.charAt(h)){g=!1;break}if(!0===g&&(a[b].setVisible(!1),l[a[b].getExtraData("boxposition")]=!1,
a[b].setExtraData("boxposition",null),c--,d=!0,0===c))break}!0===d&&s_oGame.animSpentMoney(-COST_FOR_REMOVE_LETTERS)}};this.addALetter=function(){var b=!0,c=0;if(!(s_oGame.getMoney()<COST_OF_A_LETTER-1)&&y<n&&s_oGame.getMoney()>COST_OF_A_LETTER-1)for(;!0===b;){var d=Math.floor(Math.random()*n);if(!0===l[d])c===n&&(b=!1),c++;else for(a=0;a<NUM_OF_SPAWN_LETTER;a++)if(f[a].getText()===e.charAt(d)&&!1===f[a].getUsed()){f[a].setPosition(m[d].getX(),m[d].getY());f[a].block(!0);f[a].setUsed(!0);x[d]=e.charAt(d);
f[a].setExtraData("boxposition",d);l[f[a].getExtraData("boxposition")]=!0;s_oGame.animSpentMoney(-COST_OF_A_LETTER);b=!1;y++;this.checkVictory();break}}};this._onNextLevel=function(){createjs.Tween.get(p).to({alpha:0},1E3,createjs.Ease.cubicOut).call(function(){p.visible=!1});u.setVisible(!1);y=w=0;s_oGame.wordGuessed()};this.placeLetters=function(){var b=0,c=s_oSpriteLibrary.getSprite("letter");for(a=0;a<NUM_OF_SPAWN_LETTER;a++){var h=Math.floor(Math.random()*ALPHABET[d].length);a<n?(0===a%2?f[a]=
new CTextButton(CANVAS_WIDTH/2-120*b+24*NUM_OF_SPAWN_LETTER,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+750,c,e.charAt(a),PRIMARY_FONT,"#382074",66,-10):(f[a]=new CTextButton(CANVAS_WIDTH/2-120*b+24*NUM_OF_SPAWN_LETTER,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+630,c,e.charAt(a),PRIMARY_FONT,"#382074",66,-10),b++),f[a].addEventListenerWithParams(ON_MOUSE_UP,this._onChooseWord,this,e.charAt(a),a)):(0===a%2?f[a]=new CTextButton(CANVAS_WIDTH/2-120*b+24*NUM_OF_SPAWN_LETTER,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+750,c,
ALPHABET[d][h],PRIMARY_FONT,"#382074",66,-10):(f[a]=new CTextButton(CANVAS_WIDTH/2-120*b+24*NUM_OF_SPAWN_LETTER,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+630,c,ALPHABET[d][h],PRIMARY_FONT,"#382074",66,-10),b++),f[a].addEventListenerWithParams(ON_MOUSE_UP,this._onChooseWord,this,ALPHABET[d][h],a));!1===s_bMobile&&f[a].setCursorType("pointer")}t.block(!1);v.block(!1)};this.returnPosition=function(b,c,d,e,h){f[d].setPosition(b,c);f[d].addEventListenerWithParams(ON_MOUSE_UP,this._onChooseWord,this,e,d);f[d].setUsed(!1);
x[h]=null;A=!0;createjs.Sound.play("click");!0===r.visible&&createjs.Tween.get(r).to({alpha:0},500,createjs.Ease.cubicOut).call(function(){r.visible=!1});l[h]=!1;a=0;for(b=!1;a<n&&!1===b;)!1===l[a]&&(w=a,b=!0),a++};this.shuffleLetters=function(){for(a=0;a<NUM_OF_SPAWN_LETTER;a++){var b=Math.floor(Math.random()*NUM_OF_SPAWN_LETTER),c=f[a].getX(),d=f[a].getY();f[a].setPosition(f[b].getX(),f[b].getY());f[b].setPosition(c,d)}};this._onChooseWord=function(a,b){if(w<n){for(var c=0,d=!1;c<n&&!1===d;)!1===
l[c]?(f[b].addEventListenerWithParams(ON_MOUSE_UP,this.returnPosition,this,f[b].getX(),f[b].getY(),b,f[b].getText(),c),f[b].setPosition(m[c].getX(),m[c].getY()),x[c]=a,l[c]=!0,f[b].setExtraData("boxposition",c),f[b].setUsed(!0),d=!0):w++,c++;w=c}createjs.Sound.play("click");this.checkVictory()};this.checkVictory=function(){var b=0;for(a=0;a<n;a++)!0===l[a]&&b++;if(!(b<n)&&b===n){b=!0;for(a=0;a<n;a++)x[a]!==e.charAt(a)&&(b=!1);if(!0===b){p.alpha=0;p.visible=!0;s_oStage.setChildIndex(p,s_oStage.getNumChildren()-
1);createjs.Tween.get(p).to({alpha:1},700,createjs.Ease.cubicOut);u.setVisible(!0);s_oGame.stoppedTime(!0);createjs.Sound.play("guessed");s_oGame.animEarnedMoney(n);for(a=0;a<NUM_OF_SPAWN_LETTER;a++)f[a].block(!0);for(b=0;b<NUMBER_QUEST_IMAGE;b++)c[h][b].block(!0);$(s_oMain).trigger("end_level",{ilevel:h});t.block(!0);v.block(!0)}else r.alpha=0,r.visible=!0,s_oStage.setChildIndex(r,s_oStage.getNumChildren()-1),createjs.Tween.get(r).to({alpha:1},700,createjs.Ease.cubicOut),!0===A&&(createjs.Sound.play("wrong"),
A=!1)}};this.setLevel=function(a){h=a};this.showPicture=function(){c[h][0].setPosition(CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-100);!1===s_bMobile&&c[h][0].setCursorType("pointer");switch(NUMBER_QUEST_IMAGE){case 2:c[h][1].setPosition(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-100);c[h][1].setCursorType("pointer");break;case 3:c[h][1].setPosition(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-100);c[h][2].setPosition(CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+
200);!1===s_bMobile&&(c[h][1].setCursorType("pointer"),c[h][2].setCursorType("pointer"));break;case 4:c[h][1].setPosition(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-100),c[h][2].setPosition(CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+200),c[h][3].setPosition(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+200),!1===s_bMobile&&(c[h][1].setCursorType("pointer"),c[h][2].setCursorType("pointer"),c[h][3].setCursorType("pointer"))}for(a=0;4>a;a++)this.addEventForImage(a,0);
n=e.length;var b=s_oSpriteLibrary.getSprite("letterbox");for(a=0;a<n;a++)m[a]=new CGfxButton(CANVAS_WIDTH/2+115*a-50*n,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+470,b,!0),m[a].block(!0),l[a]=!1};this.addEventForImage=function(a,b,d,e,f){0===b&&c[h][a].addEventListenerWithParams(ON_MOUSE_UP,this.zoomImage,this,c[h][a].getX(),c[h][a].getY(),c[h][a].getScale(),a);1===b&&(c[h][a].setPosition(d,e),c[h][a].setScale(f),c[h][a].addEventListenerWithParams(ON_MOUSE_UP,this.zoomImage,this,d,e,f,a),k[h][a].setVisible(!1))};
this.zoomImage=function(a,b,d,e){c[h][e].setPosition(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+50);c[h][e].setScale(2);c[h][e].changeChildIndex(s_oStage.getNumChildren()-5);c[h][e].addEventListenerWithParams(ON_MOUSE_UP,this.addEventForImage,this,e,1,a,b,d);k[h][e].setVisible(!0);k[h][e].changeChildIndex(s_oStage.getNumChildren()-4)};s_oGameSettings=this;this._init()}var s_oGameSettings;
function CGameOver(b){var g,d,e,c,k,a,m,l,f,n,w,u;this._init=function(){var r;u=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(u);$(s_oMain).trigger("save_score",s_oGame.getMoney());r=createBitmap(s_oSpriteLibrary.getSprite("bg_gameover"));s_oStage.addChild(r);r=s_oSpriteLibrary.getSprite("money_panel");k=new CTextButton(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2,r,b,PRIMARY_FONT,"#ffffff",50,-8);k.block(!0);k.setScale(1);r=s_oSpriteLibrary.getSprite("but_menu");e=new CGfxButton(CANVAS_WIDTH/
2,CANVAS_HEIGHT/2+270,r);e.addEventListener(ON_MOUSE_UP,this._onButToMenuRelease,this);m=new createjs.Text(TEXT_GAMEOVER,"bold 136px "+PRIMARY_FONT,"#ff21fe");m.textAlign="center";m.textBaseline="alphabetic";m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2-170;s_oStage.addChild(m);l=new createjs.Text(TEXT_GAMEOVER,"bold 136px "+PRIMARY_FONT,"#ffffff");l.textAlign="center";l.textBaseline="alphabetic";l.x=CANVAS_WIDTH/2;l.y=CANVAS_HEIGHT/2-170;l.outline=4;s_oStage.addChild(l);r=CANVAS_WIDTH/2-180;var p=CANVAS_HEIGHT/
2+25;f=new createjs.Text(TEXT_SCORE,"bold 96px "+PRIMARY_FONT,"#ff21fe");f.textAlign="center";f.textBaseline="alphabetic";f.x=r;f.y=p;s_oStage.addChild(f);n=new createjs.Text(TEXT_SCORE,"bold 96px "+PRIMARY_FONT,"#ffffff");n.textAlign="center";n.textBaseline="alphabetic";n.x=r;n.y=p;n.outline=4;s_oStage.addChild(n);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p=s_oSpriteLibrary.getSprite("audio_icon"),r=CANVAS_WIDTH-p.width/2-100,g=r-15,d=p.height/2+110,a=new CToggle(g,d,p,s_bAudioActive),a.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(c);createjs.Tween.get(c).to({alpha:0},1E3).call(function(){c.visible=!1})};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.unload(),a=null;k.unload();k=null;e.unload();e=null;s_oStage.removeChild(w,u,l,l,f,n);s_oGameOver=n=f=l=m=u=w=null};this._onButToMenuRelease=function(){$(s_oMain).trigger("show_interlevel_ad");this.unload();!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoMenu()};s_oGameOver=this;this._init()}var s_oGameOver;
function CGame(b,g){var d,e,c,k,a,m,l,f,n;this._init=function(){N_MAX_WORDS_TO_GUESS>NUMBER_OF_WORDS&&(N_MAX_WORDS_TO_GUESS=NUMBER_OF_WORDS);c=0;a=START_MONEY;n=0;e=new CGameSettings(b,c);e.loadQuest();e.showPicture();e.placeLetters();e.shuffleLetters();d=new CInterface(a);d.refreshNuMLevel(c);d.refreshMoney(a);$(s_oMain).trigger("start_level",{ilevel:c});k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);var g=s_oSpriteLibrary.getSprite("curtain_dx");l=createBitmap(g);
l.x=CANVAS_WIDTH;l.visible=!1;s_oStage.addChild(l);g=s_oSpriteLibrary.getSprite("curtain_sx");f=createBitmap(g);f.x=0;f.regX=g.width;f.visible=!1;s_oStage.addChild(f);f.addEventListener("click",function(){});l.addEventListener("click",function(){});s_oStage.addChild(k);createjs.Tween.get(k).to({alpha:0},1E3).call(function(){k.visible=!1})};this.wordGuessed=function(){c++;c<N_MAX_WORDS_TO_GUESS?(s_oStage.setChildIndex(l,s_oStage.getNumChildren()-1),s_oStage.setChildIndex(f,s_oStage.getNumChildren()-
1),l.visible=!0,f.visible=!0,createjs.Tween.get(f,{override:!0}).to({x:CANVAS_WIDTH/2},700,createjs.Ease.cubicOut),createjs.Tween.get(l,{override:!0}).to({x:CANVAS_WIDTH/2},700,createjs.Ease.cubicOut).call(function(){s_oGame.goToNextLevel(c,a)})):($(s_oMain).trigger("share_event",a),this.unload(),s_oMain.gotoGameOver(a))};this.goToNextLevel=function(a,b){e.setLevel(a);e.unloadQuest(c-1);e.loadQuest();e.showPicture();e.placeLetters();e.shuffleLetters();d.refreshNuMLevel(a);d.refreshMoney(b);d.resetCounter();
s_oStage.setChildIndex(l,s_oStage.getNumChildren()-1);s_oStage.setChildIndex(f,s_oStage.getNumChildren()-1);var g=s_oSpriteLibrary.getSprite("logo"),k=createBitmap(g);k.x=CANVAS_WIDTH/2;k.y=0;k.regX=g.width/2;k.regY=g.height/2;s_oStage.addChild(k);createjs.Tween.get(k,{override:!0}).to({y:CANVAS_HEIGHT/2},1300,createjs.Ease.elasticOut).call(function(){n++;n===NUM_QUIZ_FOR_ADS&&(n=0,$(s_oMain).trigger("show_interlevel_ad"));createjs.Tween.get(f,{override:!0}).wait(200).to({x:0},700,createjs.Ease.cubicOut);
createjs.Tween.get(l,{override:!0}).wait(200).to({x:CANVAS_WIDTH},700,createjs.Ease.cubicOut).call(function(){f.visible=!1;l.visible=!1;$(s_oMain).trigger("start_level",{ilevel:a});!0===BONUS_TIME&&s_oGame.stoppedTime(!1)});createjs.Tween.get(k,{override:!0}).wait(100).to({y:-g.height},700,createjs.Ease.backIn).call(function(){s_oStage.removeChild(k);k=null})})};this.animEarnedMoney=function(b){m=b+d.getCount();a+=m;d.addedMoneyAnim(m,2E3,"#00ff00");d.refreshMoney(a)};this.animSpentMoney=function(a){this.manageMoney(a);
d.addedMoneyAnim(a,2E3,"#ff0000")};this.manageMoney=function(b){a+=b;d.refreshMoney(a)};this.getMoney=function(){return a};this.restartGame=function(){this.unload();this._init()};this.stoppedTime=function(a){d.setStoppedTime(a)};this.unload=function(){d.unload();e.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("restart")};this.update=
function(){!0===BONUS_TIME&&d.update()};s_oGame=this;N_MAX_WORDS_TO_GUESS=g.words_to_guess;NUM_OF_SPAWN_LETTER=g.spawn_letters;START_MONEY=g.start_money;COST_OF_A_LETTER=g.cost_of_a_letter;COST_FOR_REMOVE_LETTERS=g.cost_for_remove_letters;TIME_FOR_EVERY_WORD=g.time_for_every_quest;NUM_QUIZ_FOR_ADS=g.num_quiz_before_ads;this._init()}var s_oGame;
function CSpriteLibrary(){var b,g,d,e,c,k;this.init=function(a,m,l){d=g=0;e=a;c=m;k=l;b={}};this.addSprite=function(a,c){b.hasOwnProperty(a)||(b[a]={szPath:c,oSprite:new Image},g++)};this.getSprite=function(a){return b.hasOwnProperty(a)?b[a].oSprite:null};this._onSpritesLoaded=function(){c.call(k)};this._onSpriteLoaded=function(){e.call(k);++d===g&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in b)b[a].oSprite.oSpriteLibrary=this,b[a].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
b[a].oSprite.src=b[a].szPath};this.getNumSprites=function(){return g}}
var CANVAS_WIDTH=1280,CANVAS_HEIGHT=1920,EDGEBOARD_X=120,EDGEBOARD_Y=80,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="ArialRoundedMTBold",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_LANGUAGE=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,LANGUAGE_EN=0,LANGUAGE_FR=1,LANGUAGE_IT=2,LANGUAGE_ES=3,LANGUAGE_GER=4,LANGUAGE_POR=5,PADDING=40,GAME_ELEMENT_HEIGHT=-150,NUMBER_OF_WORDS=21,NUMBER_QUEST_IMAGE=4,BONUS_TIME=!0,ALPHABET=[],ALPHABET=
["AAABCDEEEFGHHIIJKLMNNOOOPQRSSTTTUVWXYZ".split(""),"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split(""),"AAABCDEEEFGHIIIJKLLMNNOOPQRSTTUVWLXYZ".split(""),"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split(""),"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split(""),"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("")];
function CToggle(b,g,d,e){var c,k,a,m;this._init=function(b,d,e,g){k=[];a=[];var u=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:e.width/2/2,regY:e.height/2},animations:{state_true:[0],state_false:[1]}});c=g;m=createSprite(u,"state_"+c,e.width/2/2,e.height/2,e.width/2,e.height);m.x=b;m.y=d;m.stop();s_oStage.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown",this.buttonDown);m.off("pressup",this.buttonRelease);s_oStage.removeChild(m)};this._initListener=
function(){m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.addEventListener=function(b,c,d){k[b]=c;a[b]=d};this.setActive=function(a){c=a;m.gotoAndStop("state_"+c)};this.setCursorType=function(a){m.cursor=a};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");c=!c;m.gotoAndStop("state_"+c);k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(a[ON_MOUSE_UP],c)};this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9;k[ON_MOUSE_DOWN]&&
k[ON_MOUSE_DOWN].call(a[ON_MOUSE_DOWN])};this.setPosition=function(a,b){m.x=a;m.y=b};this._init(b,g,d,e)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(b){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(b)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(b.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(b){console.log(b)}function isIphone(){return-1!==navigator.userAgent.toLowerCase().indexOf("iphone")?!0:!1}
function getSize(b){var g=b.toLowerCase(),d=window.document,e=d.documentElement;if(void 0===window["inner"+b])b=e["client"+b];else if(window["inner"+b]!=e["client"+b]){var c=d.createElement("body");c.id="vpw-test-b";c.style.cssText="overflow:scroll";var k=d.createElement("div");k.id="vpw-test-d";k.style.cssText="position:absolute;top:-1000px";k.innerHTML="<style>@media("+g+":"+e["client"+b]+"px){body#vpw-test-b div#vpw-test-d{"+g+":7px!important}}</style>";c.appendChild(k);e.insertBefore(c,d.head);
b=7==k["offset"+b]?e["client"+b]:window["inner"+b];e.removeChild(c)}else b=window["inner"+b];return b}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var b=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<b?b:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var b;b=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var g=getSize("Width"),d=Math.min(b/CANVAS_HEIGHT,g/CANVAS_WIDTH),e=CANVAS_WIDTH*d,d=CANVAS_HEIGHT*d,c=0;d<b?(c=b-d,d+=c,e+=CANVAS_WIDTH/CANVAS_HEIGHT*c):e<g&&(c=g-e,e+=c,d+=CANVAS_HEIGHT/CANVAS_WIDTH*c);var c=b/2-d/2,k=g/2-e/2,a=CANVAS_WIDTH/e;if(k*a<-EDGEBOARD_X||c*a<-EDGEBOARD_Y)d=Math.min(b/(CANVAS_HEIGHT-2*EDGEBOARD_Y),g/(CANVAS_WIDTH-2*
EDGEBOARD_X)),e=CANVAS_WIDTH*d,d*=CANVAS_HEIGHT,c=(b-d)/2,k=(g-e)/2,a=CANVAS_WIDTH/e;s_iOffsetX=-1*k*a;s_iOffsetY=-1*c*a;0<=c&&(s_iOffsetY=0);0<=k&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",e+"px");$("#canvas").css("height",d+"px");0>c?$("#canvas").css("top",c+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",k+"px")}}
function createBitmap(b,g,d){var e=new createjs.Bitmap(b),c=new createjs.Shape;g&&d?c.graphics.beginFill("#fff").drawRect(0,0,g,d):c.graphics.beginFill("#ff0").drawRect(0,0,b.width,b.height);e.hitArea=c;return e}function createSprite(b,g,d,e,c,k){b=null!==g?new createjs.Sprite(b,g):new createjs.Sprite(b);g=new createjs.Shape;g.graphics.beginFill("#000000").drawRect(-d,-e,c,k);b.hitArea=g;return b}
function randomFloatBetween(b,g,d){"undefined"===typeof d&&(d=2);return parseFloat(Math.min(b+Math.random()*(g-b),g).toFixed(d))}function formatTime(b){b/=1E3;var g=Math.floor(b/60);b=Math.floor(b-60*g);var d="",d=10>g?d+("0"+g+":"):d+(g+":");return 10>b?d+("0"+b):d+b}function NoClickDelay(b){this.element=b;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(b){for(var g=b.length,d,e;0<g;)e=Math.floor(Math.random()*g),g--,d=b[g],b[g]=b[e],b[e]=d;return b}
NoClickDelay.prototype={handleEvent:function(b){switch(b.type){case "touchstart":this.onTouchStart(b);break;case "touchmove":this.onTouchMove(b);break;case "touchend":this.onTouchEnd(b)}},onTouchStart:function(b){b.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(b){this.moved=!0},onTouchEnd:function(b){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){b=document.elementFromPoint(b.changedTouches[0].clientX,b.changedTouches[0].clientY);3==b.nodeType&&(b=b.parentNode);var g=document.createEvent("MouseEvents");g.initEvent("click",!0,!0);b.dispatchEvent(g)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(b){for(var g=window.location.search.substring(1).split("&"),d=0;d<g.length;d++){var e=g[d].split("=");if(e[0]==b)return e[1]}}
function CTextToggle(b,g,d,e,c,k,a,m,l){var f=1,n,w=!1,u,r,p,v,t,h;this._init=function(a,b,c,d,e,g,f,k,m){n=!1;u=[];r=[];h=createBitmap(c);var l=Math.ceil(f/20);t=new createjs.Text(d," "+f+"px "+e,"#000000");t.textAlign="center";t.textBaseline="alphabetic";var w=t.getBounds();t.x=c.width/2+l;t.y=Math.floor(c.height/2)+w.height/3+l-7;v=new createjs.Text(d," "+f+"px "+e,g);v.textAlign="center";v.textBaseline="alphabetic";w=v.getBounds();v.x=c.width/2;v.y=Math.floor(c.height/2)+w.height/3-7;p=new createjs.Container;
p.x=a;p.y=b;p.regX=c.width/2;p.regY=c.height/2;k||(a=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}}),h=createSprite(a,"state_false",c.width/2/2,c.height/2,c.width/2,c.height),t.x=l,t.y=l+17,v.x=0,v.y=17,p.regX=0,p.regY=0);p.addChild(h,t,v);m.addChild(p);this._initListener()};this.unload=function(){p.off("mousedown");p.off("pressup");l.removeChild(p)};this.setVisible=function(a){p.visible=a};
this._initListener=function(){oParent=this;p.on("mousedown",this.buttonDown);p.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){u[a]=b;r[a]=c};this.buttonRelease=function(){n||w||(p.scaleX=1*f,p.scaleY=1*f,u[ON_MOUSE_UP]&&u[ON_MOUSE_UP].call(r[ON_MOUSE_UP]))};this.buttonDown=function(){n||w||(p.scaleX=.9*f,p.scaleY=.9*f,u[ON_MOUSE_DOWN]&&u[ON_MOUSE_DOWN].call(r[ON_MOUSE_DOWN]))};this.enable=function(){n=!1;m||h.gotoAndStop("state_true")};this.disable=function(){n=!0;m||h.gotoAndStop("state_false")};
this.setTextPosition=function(b,c){var d=Math.ceil(a/20);t.x=b+d;t.y=c+d;v.x=b;v.y=c};this.setText=function(a){v.text=a;t.text=a};this.setPosition=function(a,b){p.x=a;p.y=b};this.setX=function(a){p.x=a};this.setY=function(a){p.y=a};this.getButtonImage=function(){return p};this.getX=function(){return p.x};this.getY=function(){return p.y};this.block=function(a){w=a};this.setScale=function(a){f=a;p.scaleX=a;p.scaleY=a};this.setScaleX=function(a){h.scaleX=a};this._init(b,g,d,e,c,k,a,m,l);return this}
;
